import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer/footer";
import Banner from "@/components/banner";
import Head from "next/head";
import { ModalProvider } from "./providers/modalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Satvika Galaxy - Exclusive Elite Lifestyle - RERA Approved",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./favicon.png" />
      </head>

      <body className={inter.className}>
        <ModalProvider>
          <Navbar />
          <Banner />
          {children}
          <Footer />
        </ModalProvider>
      </body>
    </html>
  );
}
